servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
  # - name: "qwen2-5-vl-7b-awq"
  #  modelURL: "Qwen/Qwen2.5-VL-7B-Instruct-AWQ"
  # - name: "qwen2-5-vl-3b-awq"
  #   modelURL: "Qwen/Qwen2.5-VL-3B-Instruct-AWQ"
  - name: "qwen3-1-7b"
    modelURL: "Qwen/Qwen3-1.7B"
    repository: "vllm/vllm-openai"
    tag: "latest"

    replicaCount: 1

    requestCPU: 4
    requestMemory: "4Gi"
    requestGPU: 1

    pvcStorage: "30Gi"
    storageClass: "eva-agent-sc-fs"
    pvcAccessMode:
      - "ReadWriteMany"

    # Custom arguments for vllm serve
    # https://artifacthub.io/packages/helm/vllm-production-stack/vllm-stack?modal=template&template=deployment-vllm-multi.yaml
    vllmConfig:
      host: "0.0.0.0"
      # port: 9149 # use default 8000
      tensorParallelSize: 1
      gpuMemoryUtilization: 0.88
      #maxModelLen: 1800
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
