# Values for Docker Desktop eva-agent-init chart

storageClass:

  blockStorage:
    provisioner: docker.io/hostpath
    parameters:
      type: local
      fsType: ext4

  fileSystem:
    provisioner: nfs.csi.k8s.io
    parameters:
      server: localhost
      share: /mnt/eva-agent
