# Values for Minikube eva-agent-init chart

storageClass:

  blockStorage:
    provisioner: k8s.io/minikube-hostpath
    parameters:
      type: local
      fsType: ext4

  fileSystem:
    provisioner: nfs.csi.k8s.io
    parameters:
      server: localhost
      share: /mnt/eva-agent
